CREATE TABLE `registry_of_establishment` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `EIN` VARCHAR(50) NOT NULL,
    `establishment_name` VARCHAR(255) NOT NULL,
    `street` VARCHAR(255) NOT NULL,
    `city` VARCHAR(255) NOT NULL,
    `province` VARCHAR(255) NOT NULL,
    `tin` VARCHAR(50),
    `telephone` VARCHAR(50),
    `fax` VARCHAR(50),
    `email` VARCHAR(255),
    `manager_owner` VARCHAR(255),
    `business_nature` VARCHAR(255),
    `business_nature_other` VARCHAR(255),
    `filipino_male` INT DEFAULT 0,
    `resident_alien_male` INT DEFAULT 0,
    `non_resident_alien_male` INT DEFAULT 0,
    `below15_male` INT DEFAULT 0,
    `15to17_male` INT DEFAULT 0,
    `18to30_male` INT DEFAULT 0,
    `above30_male` INT DEFAULT 0,
    `filipino_female` INT DEFAULT 0,
    `resident_alien_female` INT DEFAULT 0,
    `non_resident_alien_female` INT DEFAULT 0,
    `below15_female` INT DEFAULT 0,
    `15to17_female` INT DEFAULT 0,
    `18to30_female` INT DEFAULT 0,
    `above30_female` INT DEFAULT 0,
    `labor_union` VARCHAR(255),
    `blr_registration` VARCHAR(255),
    `chemicals_used` TEXT,
    `parent_establishment` VARCHAR(255),
    `branch_street` VARCHAR(255),
    `branch_city` VARCHAR(255),
    `branch_province` VARCHAR(255),
    `capitalization` VARCHAR(255),
    `total_assets` VARCHAR(255),
    `dti_permit_path` VARCHAR(255),
    `past_application_number` VARCHAR(255),
    `past_application_date` DATE,
    `former_name` VARCHAR(255),
    `past_address` VARCHAR(255),
    `certification` BOOLEAN DEFAULT FALSE,
    `owner_president` VARCHAR(255),
    `date_filed` DATE,
    `date_approved` DATE,
    `approved_by` VARCHAR(255)
);
